version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - "9200:9200"
    volumes: 
      - es-data:/usr/share/elasticsearch/data
      - ./settings/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data:/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks: 
      - elastic
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    volumes: 
      - ./settings/kibana.yml:/usr/share/kibana/config/kibana.yml:ro   
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch       
    networks: 
      - elastic
    extra_hosts:  
      - "elasticsearch:127.0.0.1"

networks:
  elastic:
    driver: bridge

volumes:
  es-data:
    driver: local


